### ISSUE TITLE
old name in the README needs updating: "annyang-speech-recognition"

### ISSUE THREAD

**Issue by ngokevin** [lmalave/aframe-voice-command-component#5]

**Comment by lmalave** [comment]
Please see the new repo: https://github.com/lmalave/aframe-speech-command-component

Actually, index.js defines 2 components, speech-command and annyang-speech-recognition.  The idea was that a simple base annyang base implementation is provided, but other ones could be implemented separately.  Maybe it makes more sense to separate out annyang-speech-recognition to its own npm package?  The reason I didn't do that is because the speech-command component requires a speech-recognition implementation - it doesn't stand on its own, and I wanted to provide at least one self-contained implementation.

**Comment by ngokevin** [comment]
I see, thanks!
